language: elixir
sudo: true
services:
  - cassandra
elixir:
  - 1.4
  - 1.5
otp_release:
  - 19.3
  - 20.0
addons:
  apt:
    packages:
      - build-essential
git:
  depth: 1
env:
  - MIX_ENV=test
before_install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - rm deps/lz4/c_src/*.o
script: mix coveralls.travis
